services:
  mongodb:
    image: mongo:latest
    container_name: io_github_vkn_spring_mongo_junit5
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:

